name: Main News Server

on:
  push:
    branches: [master]
    paths: main_news_server/** #workflow will only wokr when this folder have changes
  pull_request:
    branches: [master]
    paths: main_news_server/**

jobs:
  main-news-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Start Node.js server
        working-directory: main_news_server
        env:
          AUTH_MONGO_URL: ${{ secrets.AUTH_MONGO_URL }}
        run: |
          npm ci
          npm run build &

  deploy-to-vercel:
    needs: main-news-server # waits till the previous job is done
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.MN_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.MN_PROJECT_ID}} #Required
